build:
  version: "3.0"
accounts:
  message : "creation api de gestion de cards api prod environnement"
  accounts:
    name : "oussama hamdane prod testing"
    email: "oussamahamdane#0@gmail.com"
  contact:
    - (212) 63386-9170
spring:
  config:
    activate:
      on-profile: "qa"