server:
  port: 8089
spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:mem:cards
    driver-class-name: org.h2.Driver
    username: oussama
    password:
  h2:
    console:
      enabled: true
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
  profiles:
    active: "qa"
build:
  version: "1.0"
accounts:
  message : "creation api de gestion de cards api"
  accounts:
    name : "oussama hamdane dev cards"
    email: "oussamahamdane#0@gmail.com"
  contact:
    - (212) 63386-9178
