server:
  port: 8089
spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:mem:cards
    driver-class-name: org.h2.Driver
    username: oussama
    password:
  h2:
    console:
      enabled: true
  profiles:
    active: "prod"
  config:
    import: "optional:configserver:http://localhost:8082/"
  application:
    name: "cards"
  rabbitmq:
    host: "localhost"
    username: "guest"
    password: "guest"
    port: 5672
management:
  endpoints:
    web:
      exposure:
        include: "*"
