services:
  rabbit:
    image: rabbitmq:4-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service

  serveurconfig:
    image: "oussama2655/config:0.3"
    container_name: config_serveur
    ports:
      - "8082:8082"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "curl http://localhost:8082/actuator/health/readiness"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts:
    image: "oussama2655/account:0.2"
    container_name: accounts-ms
    ports:
      - "8087:8087"
    depends_on:
       serveurconfig:
         condition: service_healthy
    environment:
        SPRING_APPLICATION_NAME: "account"
    extends:
      file: common-config.yml
      service: microservice-configserver-config


  cards:
    image: "oussama2655/cards:0.1"
    container_name: cards-ms
    ports:
      - "8089:8089"
    depends_on:
      serveurconfig:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "cards"
    extends:
      file: common-config.yml
      service: microservice-configserver-config
  loans:
     image: "oussama2655/loans:0.1"
     container_name: loans-ms
     ports:
       - "8085:8085"
     depends_on:
       serveurconfig:
         condition: service_healthy
     environment:
       SPRING_APPLICATION_NAME: "loans"
     extends:
       file: common-config.yml
       service: microservice-configserver-config
networks:
  eazybank:
    driver: "bridge"