services:
  accounts:
    image: "oussama2655/account:0.1"
    container_name: accounts-ms
    ports:
      - "8087:8087"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank
  cards:
    image: "oussama2655/cards:0.1"
    container_name: cards-ms
    ports:
      - "8089:8089"
    deploy:
      resources:
        limits:
          memory: 800m
    networks:
      - eazybank
  loans:
     image: "oussama2655/loans:0.1"
     container_name: loans-ms
     ports:
       - "8085:8085"
     deploy:
       resources:
         limits:
           memory: 500m
     networks:
      - eazybank
networks:
  eazybank:
    driver: "bridge"