server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/loans
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  profiles:
    active: "qa"
  config:
    import: "optional:configserver:http://localhost:8082/"
  application:
    name: "loans"
  rabbitmq:
    port: 5672
    username: "guest"
    password: "guest"
    host: "localhost"
management:
  endpoints:
    web:
      exposure:
        include: "*"
