spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    password:
    username: oussama
    url: jdbc:h2:mem:loans
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  web:
    error:
      include-stacktrace: never
  profiles:
    active: "qa"
  config:
    import: "optional:configserver:http://localhost:8082/"
  application:
    name: "loans"
  rabbitmq:
    port: 5672
    username: "guest"
    password: "guest"
    host: "localhost"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8084/eureka/
info:
  app:
    name: "Loans"
    description: "loans microsevices"
    version : 1,0