spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    password:
    username: oussama
    url: jdbc:h2:mem:loans
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  web:
    error:
      include-stacktrace: never
  config:
    activate:
      - "application_qa.yml"
      - "application_qa.yml"
  profiles:
    active: "qa"
server:
  port: 8085
build:
  version: "1.0"
contact:
  message : "Microservices de gestion de loans via restapi"
  contact :
    name: "oussama hamddane env enviromenent"
    email: "oussamahamdane@gmail.com"
  support:
    - (212)63386-9178



