
server:
  port: 8085
build:
  version: "1.0"
contact:
  message : "Microservices de gestion de loans via restapi"
  contact :
    name: "oussama hamddane env enviromenent"
    email: "oussamahamdane@gmail.com"
  support:
    - (212)63386-9178



