services:
  accountdb:
    image: mysql
    container_name: accountdb
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: accountdb
    extends:
      service: connection-data-base
      file: common-config.yml
  loansdb:
    image: mysql
    container_name: loansdb
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: loans
    extends:
      service: connection-data-base
      file: common-config.yml
  cardsdb:
    image: mysql
    container_name: cardsdb
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: cards
    extends:
      service: connection-data-base
      file: common-config.yml
  rabbit:
    image: rabbitmq:4-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service

  serveurconfig:
    image: "oussama2655/config:0.4"
    container_name: config_serveur
    ports:
      - "8082:8082"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "curl http://localhost:8082/actuator/health/readiness"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts:
    image: "oussama2655/account:0.4"
    container_name: accounts-ms
    ports:
      - "8087:8087"
    depends_on:
       serveurconfig:
         condition: service_healthy
       accountdb:
         condition: service_healthy

    environment:
        SPRING_APPLICATION_NAME: "account"
        SPRING_DATASOURCE_URL: "jdbc:mysql://accountdb:3306/accountdb"
    extends:
      file: common-config.yml
      service: microservice-configserver-config
  cards:
    image: "oussama2655/cards:0.3"
    container_name: cards-ms
    ports:
      - "8089:8089"
    depends_on:
      serveurconfig:
        condition: service_healthy
      cardsdb:
        condition: service_healthy

    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3306/cards"
    extends:
      file: common-config.yml
      service: microservice-configserver-config
  cards2:
    image: "oussama2655/cards:0.3"
    container_name: cards-ms2
    ports:
      - "8189:8089"
    depends_on:
      serveurconfig:
        condition: service_healthy
      cardsdb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3306/cards"
    extends:
      file: common-config.yml
      service: microservice-configserver-config
  loans:
     image: "oussama2655/loans:0.3"
     container_name: loans-ms
     ports:
       - "8085:8085"
     depends_on:
       serveurconfig:
         condition: service_healthy
       loansdb:
        condition: service_healthy
     environment:
       SPRING_APPLICATION_NAME: "loans"
       SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3306/loans"
     extends:
       file: common-config.yml
       service: microservice-configserver-config
  eurekaServer:
    image: oussama2655/eurekaserver:0.2
    container_name: eurekaserver
    ports:
      - 8084:8084
    healthcheck:
      test: "curl http://localhost:8084/actuator/health/readiness"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
       serveurconfig:
         condition: service_healthy
    environment:
       SPRING_CONFIG_IMPORT: configserver:http://serveurconfig:8082/
    extends:
      file: common-config.yml
      service: network-deploy-service
networks:
  eazybank:
    driver: "bridge"