server:
  port: 8082
spring:
  application:
    name: "configserveur"
  profiles:
   # active: native
   active : git
  cloud:
    config:
      server:
        native:
          search-locations: "file:///C:\\Users\\oussa\\Documents\\config"
        # search-locations: "classpath:/config"
