server:
  port: 8082
spring:
  application:
    name: "configserveur"
  profiles:
    # active: native
    active : git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/hamdane1548/config-files.git"
          force-pull: true
          default-label: master
          timeout: 5
          clone-on-start: true
          username: "hamdane1548"
  rabbitmq:
    port: 5672
    username: "guest"
    password: "guest"
    host: "localhost"
encrypt:
  key: "wefoinewhfnivewhrwmoirwrbvwwnvenuewfhewpifvhuweivn "
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
